version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: shadow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: shadow_dev
      # Insecure trust mode for local development; allows empty password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
    driver: local

