[build]
builder = "dockerfile"
buildCommand = ""

[deploy]
startCommand = "npm run start:production"
healthcheckPath = "/health"
healthcheckTimeout = 30

[[services]]
name = "shadow-backend"
root = "/"

  [services.env]
  NODE_ENV = "production"
  AGENT_MODE = "local"